Count proper amount of checkouts per second

diff --git a/woorricane b/woorricane
--- a/woorricane
+++ b/woorricane
@@ -162,6 +162,11 @@ function generate_json() {
     FIRST_ERROR_AT_ACTIVE=$(cat "$STEPS_PIPE/first_error_at_active")
   fi
 
+  local SUCCESSFUL_CHECKOUTS=0
+  if [ -f "$STEPS_PIPE/successful" ]; then
+    SUCCESSFUL_CHECKOUTS="$(cat "$STEPS_PIPE/successful")"
+  fi
+
   local HAS_ERROR=0
 
   STEP_JSON="{\"steps\":{}, \"active\": 0, \"max_active\": 0, \"first_error_at_active\": 0}"
@@ -173,12 +178,16 @@ function generate_json() {
       if [ -d "$STEPS_PIPE/statuses/$STEP" ] && [ -n "$(ls -A "$STEPS_PIPE/statuses/$STEP")" ]; then
         for STATUS_FILE in "$STEPS_PIPE/statuses/$STEP"/*; do
           STATUS_CODE="$(basename "$STATUS_FILE")"
-          if [ "$STATUS_CODE" -ne "200" ]; then
-            HAS_ERROR=1
-          fi
           STATUS_AMOUNT=$(wc -c < "$STATUS_FILE")
           STATUS_AMOUNT=$((STATUS_AMOUNT))
           STATUS_JSON=$(echo "$STATUS_JSON" | jq -rc ". += {\"$STATUS_CODE\": $STATUS_AMOUNT}")
+          if [ "$STATUS_CODE" -ne "200" ]; then
+            HAS_ERROR=1
+          else
+            if [ "$STEP" -eq "5" ]; then
+              SUCCESSFUL_CHECKOUTS="$STATUS_AMOUNT"
+            fi
+          fi
         done
       fi
 
@@ -201,7 +210,11 @@ function generate_json() {
     fi
   fi
 
-  STEP_JSON=$(echo "$STEP_JSON" | jq --argjson max_active "$MAX_ACTIVE" --argjson first_error "$FIRST_ERROR_AT_ACTIVE" -rc '.max_active = $max_active | .first_error_at_active = $first_error')
+  if [ "$SUCCESSFUL_CHECKOUTS" -gt 0 ]; then
+    echo "$SUCCESSFUL_CHECKOUTS" > "$STEPS_PIPE/successful"
+  fi
+
+  STEP_JSON=$(echo "$STEP_JSON" | jq --argjson max_active "$MAX_ACTIVE" --argjson first_error "$FIRST_ERROR_AT_ACTIVE" --argjson successful "$SUCCESSFUL_CHECKOUTS" -rc '.max_active = $max_active | .first_error_at_active = $first_error | .successful = $successful')
 
   echo "$STEP_JSON"
 }
@@ -240,11 +253,13 @@ function monitor() {
   local TOTAL_ACTIVE=0
   local MAX_ACTIVE=0
   local FIRST_ERROR_AT_ACTIVE=0
+  local SUCCESSFUL_CHECKOUTS=0
 
   STEP_JSON="$(generate_json)"
   TOTAL_ACTIVE=$(echo "$STEP_JSON" | jq -r '.active')
   MAX_ACTIVE=$(echo "$STEP_JSON" | jq -r '.max_active')
   FIRST_ERROR_AT_ACTIVE=$(echo "$STEP_JSON" | jq -r '.first_error_at_active')
+  SUCCESSFUL_CHECKOUTS=$(echo "$STEP_JSON" | jq -r '.successful')
 
   # Function to draw the table based on data
   draw_table() {
@@ -256,6 +271,8 @@ function monitor() {
     echo "Max Active: $MAX_ACTIVE"
     tput el       # Clear to end of line
     echo "First Error: $FIRST_ERROR_AT_ACTIVE"
+    tput el       # Clear to end of line
+    echo "Successful: $SUCCESSFUL_CHECKOUTS"
     tput el       # Clear to end of line
     echo ""
     print_table "$STEP_JSON"
@@ -286,12 +303,15 @@ function launch_monitor() {
         TOTAL_ACTIVE=$(echo "$STEP_JSON" | jq -r '.active')
         MAX_ACTIVE=$(echo "$STEP_JSON" | jq -r '.max_active')
         FIRST_ERROR_AT_ACTIVE=$(echo "$STEP_JSON" | jq -r '.first_error_at_active')
+        SUCCESSFUL_CHECKOUTS=$(echo "$STEP_JSON" | jq -r '.successful')
         tput el >&2
         echo "Total Active: $TOTAL_ACTIVE"
         tput el >&2
         echo "Max Active: $MAX_ACTIVE"
         tput el >&2
         echo "First Error: $FIRST_ERROR_AT_ACTIVE"
+        tput el >&2
+        echo "Successful: $SUCCESSFUL_CHECKOUTS"
         tput el >&2
         echo ""
 
@@ -313,13 +333,16 @@ function kill_childs() {
 
 function graceful_exit() {
   # Record the end time
+  touch "$STEPS_PIPE/monitor_exit"
+  wait
+
+  STEP_JSON="$(generate_json)"
+  SUCCESSFUL_CHECKOUTS=$(echo "$STEP_JSON" | jq -r '.successful')
+
   end_time=$(date +%s.%N)
   elapsed_time=$(echo "scale=0;$end_time - $start_time" | bc)
   tests_elapsed_time=$(echo "scale=0;$end_time - ${tests_start_time:-${end_time}}" | bc)
-  iterations_per_second=$(echo "scale=3;$USERS / $tests_elapsed_time" | bc)
-
-  touch "$STEPS_PIPE/monitor_exit"
-  wait
+  iterations_per_second=$(echo "scale=3;$SUCCESSFUL_CHECKOUTS / $tests_elapsed_time" | bc)
 
   echo ""
   echo "Script execution time: $elapsed_time seconds."
